version: '3.8'

services:
  rails_basic_auth:
    build:
      context: .
      dockerfile: Dockerfile.rails_basic_auth
    ports:
      - "9999:9999"
    container_name: rails_basic_auth
  rack_basic_auth:
    build:
      context: .
      dockerfile: Dockerfile.rack_basic_auth
    ports:
      - "9998:9998"
    container_name: rack_basic_auth
  jwt_id_server:
    build:
      context: .
      dockerfile: Dockerfile.jwt_id_server
    ports:
      - "9997:9997"
    container_name: jwt_id_server


