# Use the official Ruby image
FROM ruby:3.3.3

# Install dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

# Set up working directory
WORKDIR /app

# Copy the Gemfile and Gemfile.lock into the working directory
COPY ./src/Gemfile* ./

# Install gems
RUN gem install bundler && bundle install

# Copy the server file
COPY ./src/jwt_id_server.ru .

EXPOSE 9997

CMD ["rackup", "./jwt_id_server.ru", "-o", "0.0.0.0", "-p", "9997"]
