require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: true

Metrics/MethodLength:
  Max: 15

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
    - succeeds
    - fails
  
Performance/MethodObjectAsBlock:
  Exclude:
    - client_runner.rb
