source 'https://rubygems.org'

gem 'rails', '~> 6.1'
gem 'dbm'
gem 'rack'
gem 'thin'
gem 'jwt'
# TODO: switch to ruby debug once everything is running
gem 'pry-nav'
gem 'rspec'
# current runbook is pinned to Thor 0.20
# gem 'runbook'
gem 'rubocop'
gem 'rubocop-rspec'
gem 'rubocop-performance'
gem 'nokogiri', '1.10.10'
