# frozen_string_literal: true

source 'https://rubygems.org'

gem 'dbm'
gem 'jwt'
gem 'nokogiri'
gem 'rails'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rails'
gem 'rubocop-rspec'
gem 'thin'
